CREATE TABLE IF NOT EXISTS buyer_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_attio_id text NOT NULL REFERENCES organizations(attio_id) ON DELETE CASCADE,
  model text,
  mandate_status text,
  ebitda_floor jsonb,
  check_size_min jsonb,
  check_size_max jsonb,
  ev_ceiling jsonb,
  deal_structure_tolerance text,
  earnout_tolerance text,
  profitable_only boolean,
  investment_strategy text,
  notes text,
  key_contact_attio_id text REFERENCES people(attio_id),
  acquisition_enrichment text,
  deals_introduced integer,
  deals_converted integer,
  raw_attio jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_attio_id)
);

CREATE TABLE IF NOT EXISTS seller_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_attio_id text NOT NULL REFERENCES organizations(attio_id) ON DELETE CASCADE,
  outreach_tier text,
  appetite_signal text,
  est_revenue jsonb,
  est_ebitda jsonb,
  owner_salary jsonb,
  valuation_low jsonb,
  valuation_mid jsonb,
  valuation_high jsonb,
  sell_timeline text,
  readiness_score numeric,
  readiness_band text,
  intake_source text,
  mandate_id uuid REFERENCES mandates(id),
  last_attempt_date date,
  last_attempt_channel text,
  last_attempt_outcome text,
  lead_quality_score numeric,
  re_engage_date date,
  raw_attio jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_attio_id)
);

CREATE TABLE IF NOT EXISTS investor_lender_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_attio_id text NOT NULL REFERENCES organizations(attio_id) ON DELETE CASCADE,
  investor_type text,
  stage_focus text[] NOT NULL DEFAULT '{}',
  sector_focus text[] NOT NULL DEFAULT '{}',
  interests text,
  facility_type text,
  activity_level text,
  raw_attio jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_attio_id)
);
