"""The persistence/registry interfaces `application/attio_sync.py`/
`attio_sync_full_resync.py` depend on — implemented by
`persistence/attio_sync.py`'s free functions and
`app.modules.attio.providers.attio.registry`'s free functions,
respectively. Application code never imports either module directly.
"""

from typing import Protocol

from app.modules.attio import AttioClientProtocol


class AttioSyncRepositoryPort(Protocol):
    async def sync_organization(self, client: AttioClientProtocol, record_id: str) -> None: ...
    async def sync_person(self, client: AttioClientProtocol, record_id: str) -> None: ...
    async def sync_deal(
        self, client: AttioClientProtocol, record_id: str, *, object_slug: str = "deals"
    ) -> None: ...
    async def sync_note(self, client: AttioClientProtocol, record_id: str) -> None: ...
    async def sync_buyer_role(self, client: AttioClientProtocol, entry_id: str) -> None: ...
    async def sync_seller_role(self, client: AttioClientProtocol, entry_id: str) -> None: ...
    async def delete_organization(self, record_id: str) -> None: ...
    async def delete_person(self, record_id: str) -> None: ...


class AttioRegistryPort(Protocol):
    async def object_slug(self, client: AttioClientProtocol, object_id: str) -> str | None: ...
    async def list_slug(self, client: AttioClientProtocol, list_id: str) -> str | None: ...
