"""The persistence interface for the sellers concept — implemented by
`persistence/repositories/sellers_repository.py`. Same rationale as
`application.ports.buyers.BuyerRepositoryPort`: no domain layer, the Port's
methods return the ORM row directly.
"""

from typing import Protocol

from app.models import SellerRole


class SellerRepositoryPort(Protocol):
    async def get_by_id(self, seller_role_id: str) -> SellerRole | None: ...
    async def get_with_organization(self, seller_role_id: str) -> SellerRole | None: ...
    async def get_by_org_attio_id(self, org_attio_id: str) -> SellerRole | None: ...
    async def create(self, org_attio_id: str, **fields) -> SellerRole: ...
    async def search_by_organization_name(self, term: str, limit: int = 10) -> list[SellerRole]: ...
    async def update(self, seller_role_id: str, **fields) -> SellerRole | None: ...
