"""drop tool_runs idempotency_key uniqueness (2026-09-17)

`idempotency_key` used to block a repeat submission from the same client
(email+domain) for the same tool. The lead-magnet dedup rules changed: every
submission now gets its own permanent `tool_runs` row -- nothing is ever
blocked or merged, so nothing should enforce single-row-ness on this column
any more. The column itself stays; it still tags a row with which client it
belongs to, for grouping/lookup, just without a uniqueness guarantee.

Hand-written, not autogenerated.

`downgrade()` is a one-way door in practice: once this has been running for
real, `tool_runs` accumulates multiple rows sharing the same
`idempotency_key` by design (that's the whole point of the change), so
recreating the unique constraint will fail with a Postgres unique-violation
against that accumulated data. Only safe to downgrade immediately after
upgrading, before any real traffic lands.

Revision ID: 14fdcfc2860d
Revises: f2b8d1c47e93
Create Date: 2026-09-17 14:03:00.135653

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14fdcfc2860d"
down_revision: str | Sequence[str] | None = "f2b8d1c47e93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.drop_constraint("tool_runs_idempotency_key_key", "tool_runs", type_="unique")


def downgrade() -> None:
    op.create_unique_constraint("tool_runs_idempotency_key_key", "tool_runs", ["idempotency_key"])
