"""make exact-retry collapse atomic via partial unique index (2026-09-17)

`ToolRunsRepository.start()` collapses an exact retry of the same request
(same `tool` + `payload.submission_id`) onto its original row via a plain
`SELECT` before the `INSERT`. Two truly simultaneous retries could each miss
the other's not-yet-committed row and both insert -- a narrow, previously
accepted race.

This closes it with a genuine DB-level guarantee: `submission_id` has no
column of its own (see `tool_runs.payload`'s own docstring on why), so a
plain `UNIQUE (tool, submission_id)` constraint isn't directly expressible.
A partial, expression unique index on `(tool, payload ->> 'submission_id')`,
scoped to rows that actually have one, does the same job and lets
`start()` become a single atomic `INSERT ... ON CONFLICT DO NOTHING`.

Must match `app/models/tool_run.py::ToolRun.__table_args__`'s `Index`
exactly, same rule as `meetings`' own partial indexes
(`2565f7950641_add_desktop_push_status_columns_to_.py`) -- otherwise
`alembic check` reports drift on every autogenerate.

Hand-written, not autogenerated.

Revision ID: 542a6679b9e4
Revises: 14fdcfc2860d
Create Date: 2026-09-17 18:38:42.676289

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "542a6679b9e4"
down_revision: str | Sequence[str] | None = "14fdcfc2860d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_INDEX_NAME = "uq_tool_runs_tool_submission_id"


def upgrade() -> None:
    op.create_index(
        _INDEX_NAME,
        "tool_runs",
        ["tool", sa.text("(payload ->> 'submission_id')")],
        unique=True,
        postgresql_where=sa.text("(payload ->> 'submission_id') IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(_INDEX_NAME, table_name="tool_runs")
