"""drop buyer_roles.mandate_details (2026-08-23)

Redundant with the existing `buyer_roles.investment_strategy` column -- same
information, two places to maintain it. The DEV Attio attribute of the same
name (Buyer Role list) was archived, not hard-deleted (Attio doesn't support
that); see `workflows/crm-sync/scripts/config/migration-decisions.json`'s
`dropped_fields.buyer_role.mandate_details`. `sync-postgres.ps1` and the
`workflows/wusool-toolkit` webhook upsert no longer read or write it.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against), following the same precedent as `f3a8c1d92b47`
and `9c4d71ea2b56`.

Revision ID: 7b3f0d5e9a41
Revises: 9c4d71ea2b56
Create Date: 2026-08-23 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b3f0d5e9a41"
down_revision: str | Sequence[str] | None = "9c4d71ea2b56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("buyer_roles", "mandate_details")


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column("buyer_roles", sa.Column("mandate_details", sa.Text(), nullable=True))
