"""create all tables

Revision ID: 87320bb9dc8d
Revises: d982478fc6e3
Create Date: 2026-08-18 00:19:09.676692

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87320bb9dc8d'
down_revision: str | Sequence[str] | None = 'd982478fc6e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attio_raw_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('attio_sync_state',
    sa.Column('sync_name', sa.Text(), nullable=False),
    sa.Column('last_cursor', sa.Text(), nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sync_name')
    )
    op.create_table('users',
    sa.Column('attio_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('access', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('attio_id')
    )
    op.create_table('vertical_kb',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('tier1_research', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_cite', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vertical_kb_sector', 'vertical_kb', ['sector'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_attio_id', sa.Text(), nullable=True),
    sa.Column('subject_uuid', sa.UUID(), nullable=True),
    sa.Column('actor_attio_id', sa.Text(), nullable=True),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('subject_attio_id IS NOT NULL OR subject_uuid IS NOT NULL', name='activities_subject_present'),
    sa.ForeignKeyConstraint(['actor_attio_id'], ['users.attio_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_subject', 'activities', ['subject_type', 'subject_attio_id'], unique=False)
    op.create_index('idx_activities_ts', 'activities', [sa.literal_column('ts DESC')], unique=False)
    op.create_table('organizations',
    sa.Column('attio_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('client_type', sa.Text(), nullable=True),
    sa.Column('sector_focus', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('stage_focus', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('geographic_focus', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('hq_country', sa.Text(), nullable=True),
    sa.Column('domains', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('relationship_status', sa.Text(), nullable=True),
    sa.Column('connection_strength', sa.Text(), nullable=True),
    sa.Column('owner_attio_id', sa.Text(), nullable=True),
    sa.Column('last_interaction_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estimated_arr', sa.Text(), nullable=True),
    sa.Column('funding_raised', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('removed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_attio_id'], ['users.attio_id'], name='organizations_owner_attio_id_fkey'),
    sa.PrimaryKeyConstraint('attio_id')
    )
    op.create_index('idx_organizations_domains', 'organizations', ['domains'], unique=False, postgresql_using='gin')
    op.create_index('idx_organizations_type', 'organizations', ['type'], unique=False, postgresql_using='gin')
    op.create_index('ix_organizations_name_trgm', 'organizations', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('scorecards',
    sa.Column('attio_id', sa.Text(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('created_by_attio_id', sa.Text(), nullable=True),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_attio_id'], ['users.attio_id'], ),
    sa.PrimaryKeyConstraint('attio_id')
    )
    op.create_index('idx_scorecards_week_start', 'scorecards', [sa.literal_column('week_start DESC')], unique=False)
    op.create_table('buyer_intel',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('buyer_attio_id', sa.Text(), nullable=False),
    sa.Column('cash_window', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('appetite_score', sa.Numeric(), nullable=True),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('ideal_target', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brief_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['buyer_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buyer_intel_buyer_generated', 'buyer_intel', ['buyer_attio_id', sa.literal_column('generated_at DESC')], unique=False)
    op.create_table('investor_lender_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_attio_id', sa.Text(), nullable=False),
    sa.Column('investor_type', sa.Text(), nullable=True),
    sa.Column('stage_focus', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('sector_focus', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('facility_type', sa.Text(), nullable=True),
    sa.Column('activity_level', sa.Text(), nullable=True),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_attio_id')
    )
    op.create_table('mandates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attio_id', sa.Text(), nullable=True),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('buyer_attio_id', sa.Text(), nullable=True),
    sa.Column('seller_attio_id', sa.Text(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('assigned_advisor_attio_ids', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('universe_constructed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('shortlist_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=True),
    sa.Column('shortlist_size', sa.Integer(), nullable=True),
    sa.Column('tier1_contacted', sa.Integer(), nullable=True),
    sa.Column('responses', sa.Integer(), nullable=True),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_attio_id'], ['organizations.attio_id'], ),
    sa.ForeignKeyConstraint(['seller_attio_id'], ['organizations.attio_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attio_id')
    )
    op.create_table('match_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('buyer_attio_id', sa.Text(), nullable=False),
    sa.Column('seller_attio_id', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('dims', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_scores_pair_generated', 'match_scores', ['buyer_attio_id', 'seller_attio_id', sa.literal_column('generated_at DESC')], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=True),
    sa.Column('org_name_raw', sa.Text(), nullable=True),
    sa.Column('counterparty_role', postgresql.ENUM('buyer', 'seller', name='counterparty_role', create_type=False), nullable=True),
    sa.Column('meeting_type', postgresql.ENUM('enrichment', 'alignment', 'owner_iv', 'buyer_intro', 'internal', name='meeting_type', create_type=False), nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source', postgresql.ENUM('in_house', 'granola', 'manual', name='meeting_source', create_type=False), server_default='in_house', nullable=False),
    sa.Column('audio_ref', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('created_by_ref', sa.Text(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scribe_meeting_id', sa.Uuid(), nullable=True),
    # Named explicitly to match database/sql/005_meetings.sql's
    # `ALTER TABLE meetings ADD CONSTRAINT fk_meetings_org ...` — that file's
    # own comment documents `DROP CONSTRAINT fk_meetings_org` as the revert
    # path, so the name is load-bearing for anyone following that runbook.
    # Autogenerate does not preserve this (it renders the Postgres default
    # `meetings_org_id_fkey` since the model's plain `ForeignKey(...)` has no
    # explicit name), so it's corrected here by hand.
    sa.ForeignKeyConstraint(
        ['org_id'], ['organizations.attio_id'], name='fk_meetings_org'
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scribe_meeting_id')
    )
    op.create_index('ix_meetings_occurred_at', 'meetings', ['occurred_at'], unique=False)
    op.create_index('ix_meetings_org_id', 'meetings', ['org_id'], unique=False)
    op.create_table('people',
    sa.Column('attio_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('company_attio_id', sa.Text(), nullable=True),
    sa.Column('email', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('relationship_status', sa.Text(), nullable=True),
    sa.Column('connection_strength', sa.Text(), nullable=True),
    sa.Column('owner_attio_id', sa.Text(), nullable=True),
    sa.Column('past_employers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_interaction_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_attio_id'], ['organizations.attio_id'], ),
    sa.ForeignKeyConstraint(['owner_attio_id'], ['users.attio_id'], name='people_owner_attio_id_fkey'),
    sa.PrimaryKeyConstraint('attio_id')
    )
    op.create_index('idx_people_company', 'people', ['company_attio_id'], unique=False)
    op.create_index('idx_people_email', 'people', ['email'], unique=False, postgresql_using='gin')
    op.create_table('seller_financials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('seller_attio_id', sa.Text(), nullable=False),
    sa.Column('normalised_ebitda_sde', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('add_backs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('proxy_revenue', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('source_cite', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_seller_financials_seller', 'seller_financials', ['seller_attio_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('buyer_attio_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('source_cite', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_buyer_ts', 'signals', ['buyer_attio_id', sa.literal_column('ts DESC')], unique=False)
    op.create_table('buyer_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_attio_id', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('mandate_status', sa.Text(), nullable=True),
    sa.Column('ebitda_floor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('check_size_min', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('check_size_max', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ev_ceiling', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deal_structure_tolerance', sa.Text(), nullable=True),
    sa.Column('earnout_tolerance', sa.Text(), nullable=True),
    sa.Column('profitable_only', sa.Boolean(), nullable=True),
    sa.Column('investment_strategy', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('key_contact_attio_id', sa.Text(), nullable=True),
    sa.Column('acquisition_enrichment', sa.Text(), nullable=True),
    sa.Column('deals_introduced', sa.Integer(), nullable=True),
    sa.Column('deals_converted', sa.Integer(), nullable=True),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['key_contact_attio_id'], ['people.attio_id'], ),
    sa.ForeignKeyConstraint(['org_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_attio_id')
    )
    op.create_table('deals',
    sa.Column('attio_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('stage_changed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('buyer_organization_attio_id', sa.Text(), nullable=True),
    sa.Column('buyer_person_attio_id', sa.Text(), nullable=True),
    sa.Column('seller_organization_attio_id', sa.Text(), nullable=True),
    sa.Column('owner_attio_id', sa.Text(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('teaser_status', sa.Text(), nullable=True),
    sa.Column('nda_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cim_ready', sa.Boolean(), nullable=True),
    sa.Column('deal_memo_ready', sa.Boolean(), nullable=True),
    sa.Column('contract_signed_date', sa.Date(), nullable=True),
    sa.Column('exclusivity_date', sa.Date(), nullable=True),
    sa.Column('next_task', sa.Text(), nullable=True),
    sa.Column('data_room_substatus', sa.Text(), nullable=True),
    sa.Column('comparables', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_in_stage', sa.Interval(), nullable=True),
    sa.CheckConstraint('buyer_organization_attio_id IS NULL OR buyer_person_attio_id IS NULL', name='deals_one_buyer'),
    sa.ForeignKeyConstraint(['buyer_organization_attio_id'], ['organizations.attio_id'], ),
    sa.ForeignKeyConstraint(['buyer_person_attio_id'], ['people.attio_id'], ),
    sa.ForeignKeyConstraint(['owner_attio_id'], ['users.attio_id'], name='deals_owner_attio_id_fkey'),
    sa.ForeignKeyConstraint(['seller_organization_attio_id'], ['organizations.attio_id'], ),
    sa.PrimaryKeyConstraint('attio_id')
    )
    op.create_index('idx_deals_buyer_org', 'deals', ['buyer_organization_attio_id'], unique=False)
    op.create_index('idx_deals_seller_org', 'deals', ['seller_organization_attio_id'], unique=False)
    op.create_index('idx_deals_stage', 'deals', ['stage'], unique=False)
    op.create_index('idx_deals_stage_changed_at', 'deals', [sa.literal_column('stage_changed_at DESC')], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_a_attio_id', sa.Text(), nullable=False),
    sa.Column('person_b_attio_id', sa.Text(), nullable=False),
    sa.Column('hop', sa.Text(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.Column('source_cite', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('person_a_attio_id <> person_b_attio_id', name='graph_edges_not_self'),
    sa.ForeignKeyConstraint(['person_a_attio_id'], ['people.attio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_attio_id'], ['people.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_graph_edges_people', 'graph_edges', ['person_a_attio_id', 'person_b_attio_id'], unique=False)
    op.create_table('mandate_targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=False),
    sa.Column('seller_attio_id', sa.Text(), nullable=False),
    sa.Column('proxy_size', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandate_id', 'seller_attio_id', name='mandate_targets_mandate_id_seller_attio_id_key')
    )
    op.create_table('seller_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_attio_id', sa.Text(), nullable=False),
    sa.Column('outreach_tier', sa.Text(), nullable=True),
    sa.Column('appetite_signal', sa.Text(), nullable=True),
    sa.Column('relationship_status', sa.Text(), nullable=True),
    sa.Column('est_revenue', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('est_ebitda', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_salary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valuation_low', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valuation_mid', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valuation_high', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sell_timeline', sa.Text(), nullable=True),
    sa.Column('readiness_score', sa.Numeric(), nullable=True),
    sa.Column('readiness_band', sa.Text(), nullable=True),
    sa.Column('intake_source', sa.Text(), nullable=True),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('last_attempt_date', sa.Date(), nullable=True),
    sa.Column('last_attempt_channel', sa.Text(), nullable=True),
    sa.Column('last_attempt_outcome', sa.Text(), nullable=True),
    sa.Column('lead_quality_score', sa.Numeric(), nullable=True),
    sa.Column('re_engage_date', sa.Date(), nullable=True),
    sa.Column('raw_attio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.ForeignKeyConstraint(['org_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_attio_id')
    )
    op.create_index('idx_seller_roles_intake_source', 'seller_roles', ['intake_source'], unique=False)
    op.create_table('deal_stage_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_attio_id', sa.Text(), nullable=False),
    sa.Column('from_stage', sa.Text(), nullable=True),
    sa.Column('to_stage', sa.Text(), nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_attio_id'], ['deals.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deal_stage_events_deal_ts', 'deal_stage_events', ['deal_attio_id', sa.literal_column('ts DESC')], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_attio_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('output_type', sa.Text(), nullable=True),
    sa.Column('drive_ref', sa.Text(), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('qc_state', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_attio_id'], ['deals.attio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_deal_kind', 'documents', ['deal_attio_id', 'kind'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('buyer_attio_id', sa.Text(), nullable=False),
    sa.Column('buyer_role_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('seller_attio_id', sa.Text(), nullable=True),
    sa.Column('seller_role_id', sa.UUID(), nullable=True),
    sa.Column('match_score_id', sa.UUID(), nullable=True),
    sa.Column('match_score', sa.Numeric(), nullable=True),
    sa.Column('data_confidence', sa.Numeric(), nullable=True),
    sa.Column('why_chosen_over_alternatives', sa.Text(), nullable=True),
    sa.Column('recommended_pitch', sa.Text(), nullable=True),
    sa.Column('risks_and_gaps', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='GENERATED', nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('requirement_profile_version', sa.Integer(), nullable=True),
    sa.Column('requirement_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidates_considered', sa.Integer(), nullable=True),
    sa.Column('candidates_filtered', sa.Integer(), nullable=True),
    sa.Column('filters_skipped', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('vector_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_candidate_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED', 'REJECTED')", name='match_results_decision_check'),
    sa.CheckConstraint("status IN ('GENERATED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'FAILED')", name='match_results_status_check'),
    sa.ForeignKeyConstraint(['buyer_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_role_id'], ['buyer_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_score_id'], ['match_scores.id'], ),
    sa.ForeignKeyConstraint(['seller_attio_id'], ['organizations.attio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_role_id'], ['seller_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_results_buyer_role', 'match_results', ['buyer_role_id'], unique=False)
    op.create_index('idx_match_results_run_id', 'match_results', ['run_id'], unique=False)
    op.create_index('idx_match_results_status', 'match_results', ['status'], unique=False)
    op.create_index('uq_match_results_run_header', 'match_results', ['run_id'], unique=True, postgresql_where=sa.text('rank IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_match_results_run_header', table_name='match_results', postgresql_where=sa.text('rank IS NULL'))
    op.drop_index('idx_match_results_status', table_name='match_results')
    op.drop_index('idx_match_results_run_id', table_name='match_results')
    op.drop_index('idx_match_results_buyer_role', table_name='match_results')
    op.drop_table('match_results')
    op.drop_index('idx_documents_deal_kind', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_deal_stage_events_deal_ts', table_name='deal_stage_events')
    op.drop_table('deal_stage_events')
    op.drop_index('idx_seller_roles_intake_source', table_name='seller_roles')
    op.drop_table('seller_roles')
    op.drop_table('mandate_targets')
    op.drop_index('idx_graph_edges_people', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('idx_deals_stage_changed_at', table_name='deals')
    op.drop_index('idx_deals_stage', table_name='deals')
    op.drop_index('idx_deals_seller_org', table_name='deals')
    op.drop_index('idx_deals_buyer_org', table_name='deals')
    op.drop_table('deals')
    op.drop_table('buyer_roles')
    op.drop_index('idx_signals_buyer_ts', table_name='signals')
    op.drop_table('signals')
    op.drop_index('idx_seller_financials_seller', table_name='seller_financials')
    op.drop_table('seller_financials')
    op.drop_index('idx_people_email', table_name='people', postgresql_using='gin')
    op.drop_index('idx_people_company', table_name='people')
    op.drop_table('people')
    op.drop_index('ix_meetings_org_id', table_name='meetings')
    op.drop_index('ix_meetings_occurred_at', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index('idx_match_scores_pair_generated', table_name='match_scores')
    op.drop_table('match_scores')
    op.drop_table('mandates')
    op.drop_table('investor_lender_roles')
    op.drop_index('idx_buyer_intel_buyer_generated', table_name='buyer_intel')
    op.drop_table('buyer_intel')
    op.drop_index('idx_scorecards_week_start', table_name='scorecards')
    op.drop_table('scorecards')
    op.drop_index('ix_organizations_name_trgm', table_name='organizations', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_organizations_type', table_name='organizations', postgresql_using='gin')
    op.drop_index('idx_organizations_domains', table_name='organizations', postgresql_using='gin')
    op.drop_table('organizations')
    op.drop_index('idx_activities_ts', table_name='activities')
    op.drop_index('idx_activities_subject', table_name='activities')
    op.drop_table('activities')
    op.drop_index('idx_vertical_kb_sector', table_name='vertical_kb')
    op.drop_table('vertical_kb')
    op.drop_table('users')
    op.drop_table('attio_sync_state')
    op.drop_table('attio_raw_events')
    # ### end Alembic commands ###
