"""merge Mandate fields into Deal (2026-08-23)

The DEV Attio Mandates list is retired: the one-mandate-to-many-deals model
it was built for was never actually used (neither of the 2 real DEV Mandate
entries had a linked Deal), so every Mandate entry becomes its own Deal
record instead, tagged with a new `deal_type`. See
`workflows/crm-sync/scripts/config/migration-decisions.json` and the
"Wusool Schema Handover" artifact for full rationale.

Adds to `deals`: `deal_type`, `universe_constructed`, `universe_size`,
`shortlist_approved`, `shortlist_size`, `tier1_contacted`, `responses`,
`counterparty_interested` (renamed from Mandate's `sellers_interested` --
that name only reads correctly on a buy-side mandate), `mandate_start_date`
/ `mandate_expiry_date` (disambiguated from `contract_signed_date`/
`exclusivity_date`/`expected_close_date` already on Deal -- DEV Attio slugs
stayed `start_date`/`expiry_date`, only the display titles changed),
`retainer_amount`, and `source_mandate_entry_id` (idempotency key for the
migration script, not a business field -- unique so it can't collide).

Mandate's `phase` was deliberately not carried over: a manually-typed label
that only restates universe_constructed/universe_size/shortlist_approved/
shortlist_size/tier1_contacted/responses, and can drift out of sync with
those numbers. Deal's existing `assigned_advisor` (plain multiselect of
names) is reused as-is rather than replaced with Mandate's
`user-reference[]`-typed `assigned_advisor_attio_ids` -- Attio can't change
a field's type in place, and a second parallel "who's the advisor" field
would be worse than reusing this one.

The `mandates` table itself is untouched -- kept for its 2 historical rows,
not dropped. Nothing will write new rows there going forward.

All 58 pre-existing Deals were backfilled to deal_type='Sell-side' directly
in DEV Attio (`Invoke-Deals -MigrateMandates` in
`scripts/_internal/objects.ps1`), confirmed against SOURCE's `deals`
attribute list having no buyer-referencing field at all -- only
`associated_company` (-> seller). That backfill lands in Postgres through
the normal `sync-postgres.ps1 -Apply` / Attio webhook sync, not through this
migration -- this only adds the (nullable) column.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against) -- types confirmed against the real DEV Attio
attributes created via `ensure-schema.ps1 -Entities deals -Apply`, following
the same precedent as `f3a8c1d92b47`.

Revision ID: 9c4d71ea2b56
Revises: a1c5e8f34b02
Create Date: 2026-08-23 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c4d71ea2b56"
down_revision: str | Sequence[str] | None = "a1c5e8f34b02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("deals", sa.Column("deal_type", sa.Text(), nullable=True))
    op.add_column(
        "deals",
        sa.Column(
            "universe_constructed",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column("deals", sa.Column("universe_size", sa.Integer(), nullable=True))
    op.add_column(
        "deals",
        sa.Column(
            "shortlist_approved",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column("deals", sa.Column("shortlist_size", sa.Integer(), nullable=True))
    op.add_column("deals", sa.Column("tier1_contacted", sa.Integer(), nullable=True))
    op.add_column("deals", sa.Column("responses", sa.Integer(), nullable=True))
    op.add_column(
        "deals", sa.Column("counterparty_interested", sa.Integer(), nullable=True)
    )
    op.add_column("deals", sa.Column("mandate_start_date", sa.Date(), nullable=True))
    op.add_column("deals", sa.Column("mandate_expiry_date", sa.Date(), nullable=True))
    op.add_column(
        "deals",
        sa.Column("retainer_amount", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "deals",
        sa.Column("source_mandate_entry_id", sa.Text(), nullable=True, unique=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("deals", "source_mandate_entry_id")
    op.drop_column("deals", "retainer_amount")
    op.drop_column("deals", "mandate_expiry_date")
    op.drop_column("deals", "mandate_start_date")
    op.drop_column("deals", "counterparty_interested")
    op.drop_column("deals", "responses")
    op.drop_column("deals", "tier1_contacted")
    op.drop_column("deals", "shortlist_size")
    op.drop_column("deals", "shortlist_approved")
    op.drop_column("deals", "universe_size")
    op.drop_column("deals", "universe_constructed")
    op.drop_column("deals", "deal_type")
