"""add organizations.is_active (2026-08-20)

Direct 1:1 mirror of the new DEV Attio `organizations.is_active` attribute
(see the Wusool Schema Handover artifact): SOURCE Companies are grouped by
exact name (case/whitespace-insensitive), and within each group the record
with the newest SOURCE `created_at` is written `true`, every older
same-name duplicate `false`; a unique name defaults to `true`. Not filtered
on in Postgres -- `organizations` already holds one row per organization
(no duplicate rows to prefer between), unlike `buyer_roles`/`seller_roles`
where `is_active` picks which Attio list entry to write.

Hand-written, not autogenerated (no live DB connection available in this
session).

Revision ID: a1c5e8f34b02
Revises: e5b1c9a2f60d
Create Date: 2026-08-20 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1c5e8f34b02"
down_revision: str | Sequence[str] | None = "e5b1c9a2f60d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("organizations", sa.Column("is_active", sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("organizations", "is_active")
