"""add vertical-grain columns to buyer_roles and seller_roles (2026-09-21)

First migration of the vertical re-grain: `buyer_roles` becomes one row per
(organization, vertical) rather than one per organization, so an advisor can
search for sellers on behalf of one buyer, one vertical at a time.

This migration only *adds* columns. Every one is empty until the split script
runs, so applying it changes no behaviour — deliberately, so it can ship ahead
of the reconciliation change it depends on. NOT NULL on `target_vertical`, the
composite index and the one-live-row-per-(org, vertical) uniqueness rule all
come later, after the backfill has been verified.

`organizations.sector_focus` / `geographic_focus` / `stage_focus` /
`ticket_size` deliberately STAY where they are. Expand/contract: rollback stays
script-only while both sides exist, and the backfill can be verified against the
original continuously rather than once. `organizations.sector_focus` also cannot
move yet regardless — the seller side of matching still reads it for the
`sector` and `sector_exclusion` criteria until `seller_roles.sector` is
backfilled and `matching_engine/persistence/mappers.py` is repointed.

Column shapes mirror their Attio attributes (added in the same change, see
`crm-sync/scripts/source-attio/_internal/schema.ps1`):

- `buyer_roles.target_vertical` — Attio single-select, so plain text here. The
  grain itself: single-valued even though the `organizations.sector_focus` it
  derives from is a multiselect.
- `buyer_roles.geographic_focus` / `target_stage` — verbatim carry-overs of the
  same-named Organization values. Attio TEXT, comma-joined, because neither
  vocabulary is enumerated (SOURCE's `geographic_focus` is still
  `needs_approval`) and an Attio select REJECTS values outside its options —
  `Africa` and `Pakistan` have no equivalent in `target_geography`'s nine. Text
  on both sides guarantees the copy is lossless. `target_geography` stays
  authoritative for matching; these are preserved values awaiting a mapping
  decision, not a competing source.
- `buyer_roles.ticket_size` — free text on Organization too (verified live
  2026-08-30). `check_size_min` / `check_size_max` stay authoritative for
  matching; the overlap flagged in `enrichment/domain/field_plans.py` is
  resolved separately.
- `seller_roles.sector` — Attio multiselect, so `text[]` here, matching
  `organizations.sector_focus` in both vocabulary and shape. The sector a seller
  operates in: an identity, not a want, hence `sector` and not `sector_focus`.
  NOT NULL with an empty-array default, the same shape as
  `buyer_roles.target_geography` and `organizations.sector_focus` — the sync
  always writes a list, so NULL would never occur.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against).

Revision ID: a3f19c7d2e64
Revises: 542a6679b9e4
Create Date: 2026-09-21 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f19c7d2e64"
down_revision: str | Sequence[str] | None = "542a6679b9e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("buyer_roles", sa.Column("target_vertical", sa.Text(), nullable=True))
    op.add_column("buyer_roles", sa.Column("geographic_focus", sa.Text(), nullable=True))
    op.add_column("buyer_roles", sa.Column("target_stage", sa.Text(), nullable=True))
    op.add_column("buyer_roles", sa.Column("ticket_size", sa.Text(), nullable=True))
    op.add_column(
        "seller_roles",
        sa.Column(
            "sector",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
    )


def downgrade() -> None:
    op.drop_column("seller_roles", "sector")
    op.drop_column("buyer_roles", "ticket_size")
    op.drop_column("buyer_roles", "target_stage")
    op.drop_column("buyer_roles", "geographic_focus")
    op.drop_column("buyer_roles", "target_vertical")
