"""add organizations.employee_range (2026-08-19)

Adds the `employee_range` column decided today: SOURCE's own headcount bands
(1-10, 11-50, 51-250, 251-1K, 1K-5K, 5K-10K, 10K-50K, 50K-100K, 100K+) are
adopted as-is on DEV Attio and here, rather than reconciling them against the
previously-requested target bands.

Hand-written, not autogenerated (no live DB connection available in this
session).

Revision ID: a7e2f6c1d834
Revises: f3a8c1d92b47
Create Date: 2026-08-19 09:40:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7e2f6c1d834"
down_revision: str | Sequence[str] | None = "f3a8c1d92b47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("organizations", sa.Column("employee_range", sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("organizations", "employee_range")
