"""add notes.primary_role and the meeting_role enum type (2026-09-07)

`notes` gains the role the meeting it came from was about, so internal
meetings can be filtered out of the Attio UI — which is the point of adding
it. The matching Attio attribute `note.primary_role` was created the same
day as a single-select carrying the identical five option titles.

A native enum rather than text + CHECK, unlike `note_type` in
c3d7f2a856e1. Two reasons: the values are an existing domain enum
(`MeetingRole` in meetings/domain/roles.py) rather than a set invented for
one column, and the meetings module already owns three native enums that
this sits alongside conceptually.

The type is named `meeting_role`, not `primary_role`. `counterparty_role`
and `meeting_type` are both named after their single column, but this one
names the domain concept: `MeetingRole` is what it mirrors, more than one
column may come to hold it, and a type called `primary_role` says nothing
about which roles it admits.

CREATE TYPE is guarded and lives here, matching d982478fc6e3 -- the model
declares the type `create_type=False` so `--autogenerate` never re-emits it.
Do not flip that on the model: integration tests run against a real
alembic-migrated database, so flipping it would make autogenerate try to
create a type this revision already owns.

Hand-written, not autogenerated (no live DB connection in this session).

Revision ID: b4e1d7c0f3a2
Revises: f7a2c9e14b83
Create Date: 2026-09-07 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4e1d7c0f3a2"
down_revision: str | Sequence[str] | None = "f7a2c9e14b83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lowercase, and identical to the Attio select's option titles. Attio select
# values are case-sensitive and the server passes the enum string straight
# through, so the two sides must not drift.
_ROLES = ("seller", "buyer", "investor", "internal", "general")


def upgrade() -> None:
    """Upgrade schema."""
    # Guarded exactly as d982478fc6e3 does: a database that already has the
    # type (a re-run, or one restored from a snapshot taken after this ran)
    # must be a no-op rather than an error.
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'meeting_role') THEN
            CREATE TYPE meeting_role AS ENUM (
                'seller',
                'buyer',
                'investor',
                'internal',
                'general'
            );
          END IF;
        END
        $$;
        """
    )
    op.add_column(
        "notes",
        sa.Column(
            "primary_role",
            postgresql.ENUM(*_ROLES, name="meeting_role", create_type=False),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("notes", "primary_role")
    # Dropped only after the one column using it is gone. Guarded so a
    # database where something else has since adopted the type is left alone.
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM pg_attribute a
              JOIN pg_type t ON t.oid = a.atttypid
             WHERE t.typname = 'meeting_role' AND a.attisdropped = false
          ) THEN
            DROP TYPE IF EXISTS meeting_role;
          END IF;
        END
        $$;
        """
    )
