"""add people.removed_at (2026-08-23)

Mirrors organizations.removed_at (see f3a8c1d92b47): sync-postgres.ps1
soft-deletes a person no longer present in DEV Attio instead of hard
-deleting it, since buyer_roles.key_contact_attio_id and
deals.buyer_person_attio_id both reference people with ON DELETE NO ACTION
-- a hard delete would either fail outright or silently break a
still-valid buyer role/deal's contact reference if either still points at
the row being removed.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against), following the same precedent as f3a8c1d92b47,
9c4d71ea2b56, 7b3f0d5e9a41, 2e8a6c14f7b9, and a4f9e61c3d78.

Revision ID: b7c2e419d5a3
Revises: a4f9e61c3d78
Create Date: 2026-08-23 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7c2e419d5a3"
down_revision: str | Sequence[str] | None = "a4f9e61c3d78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "people", sa.Column("removed_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("people", "removed_at")
