"""add removed_at to deals, notes, buyer_roles, seller_roles (2026-09-15)

Soft-delete marker, mirroring `organizations.removed_at` (87320bb9dc8d) and
`person.removed_at` (b7c2e419d5a3). Postgres-only -- there is no Attio
attribute behind it; it is set by the webhook's delete handlers and by the
nightly resync's reconciliation, and cleared again when a record reappears.

Until now only `organizations` and `person` could record a deletion. A Deal,
Note, or Buyer/Seller Role deleted in Attio was either left in Postgres
indefinitely (notes -- nothing handled them at all) or hard-deleted by
`scripts/postgres-sync/prod/sync-source-to-prod.ps1`. Two problems with that
hard delete:

  * `deals` is the parent of `deal_stage_events` and `documents`, and both role
    tables are parents of `match_results` -- all `ON DELETE CASCADE`. Those rows
    are computed in Postgres and have no Attio counterpart, so a cascade
    destroyed data no resync could rebuild.
  * `DELETE FROM buyer_roles`/`seller_roles` fails outright once a stale role is
    referenced by `notes.{buyer,seller}_role_id` or
    `tool_runs.{buyer,seller}_role_id` -- neither declares an `ON DELETE`, so
    the delete raises a foreign-key violation and takes the whole run with it.
    Latent only because no stale role has carried a note yet.

Soft delete makes both unreachable: nothing is physically removed, so the
cascades never fire and the unguarded FKs are never violated.

This restores columns that a 2026-08 change added to `seller_roles`/
`buyer_roles` and then reverted (6b0642671e13, 8d7dcb445863) for landing
without data-engineer sign-off -- see `app/modules/ddl_commands/README.md`'s
"History: the schema-authority correction". The revert is being reversed
deliberately and with sign-off, not re-litigated by accident. Unlike that
attempt, this adds no `bot_managed_at`/`bot_managed_by` and no
`/remove-seller`//remove-buyer` command: deletion stays authored in Attio and
is only mirrored here.

`ON DELETE CASCADE` clauses are deliberately left in place. With nothing
hard-deleting these rows they are unreachable, and dropping nine constraints
would be a far larger migration for no behavioural gain.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against).

Revision ID: b8c41e7d09a2
Revises: d3f49e19fd35
Create Date: 2026-09-15 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8c41e7d09a2"
down_revision: str | Sequence[str] | None = "d3f49e19fd35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLES = ("deals", "notes", "buyer_roles", "seller_roles")


def upgrade() -> None:
    for table in _TABLES:
        op.add_column(table, sa.Column("removed_at", sa.TIMESTAMP(timezone=True), nullable=True))


def downgrade() -> None:
    for table in reversed(_TABLES):
        op.drop_column(table, "removed_at")
