"""add organizations.linkedin (2026-08-19)

Adds the `linkedin` column, migrated from SOURCE companies.linkedin (plain
text URL, no transform).

Hand-written, not autogenerated (no live DB connection available in this
session).

Revision ID: b91d4a7f0526
Revises: a7e2f6c1d834
Create Date: 2026-08-19 09:48:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b91d4a7f0526"
down_revision: str | Sequence[str] | None = "a7e2f6c1d834"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("organizations", sa.Column("linkedin", sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("organizations", "linkedin")
