"""create notes table (2026-08-28)

Unified notes table, replacing notes scattered across Organization, Person,
and Buyer Role. See `app/models/note.py`'s docstring for the full
population story (SOURCE Attio's `note` custom object, via
`database/sync-notes-from-source.ps1` -- not DEV Attio, which has no notes
object yet).

`note_type` is plain Text + a CheckConstraint, not a native Postgres enum --
no external service needs this type to exist independently of this table
(unlike meetings' Scribe-owned enums in `005_meetings.sql`).

Hand-written, not autogenerated (no live DB connection available in this
session).

Revision ID: c3d7f2a856e1
Revises: b8f4c1e93a56
Create Date: 2026-08-28 19:50:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3d7f2a856e1"
down_revision: str | Sequence[str] | None = "b8f4c1e93a56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "notes",
        sa.Column("id", postgresql.UUID(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("organization_id", sa.Text(), sa.ForeignKey("organizations.attio_id"), nullable=False),
        sa.Column("person_id", sa.Text(), sa.ForeignKey("people.attio_id"), nullable=True),
        sa.Column("buyer_role_id", postgresql.UUID(), sa.ForeignKey("buyer_roles.id"), nullable=True),
        sa.Column("seller_role_id", postgresql.UUID(), sa.ForeignKey("seller_roles.id"), nullable=True),
        sa.Column("note_type", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.CheckConstraint("note_type IN ('Manual', 'Meeting')", name="notes_note_type_check"),
    )
    op.create_index("idx_notes_organization", "notes", ["organization_id"])
    op.create_index("idx_notes_person", "notes", ["person_id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("idx_notes_person", table_name="notes")
    op.drop_index("idx_notes_organization", table_name="notes")
    op.drop_table("notes")
