"""add organizations.region (2026-09-12)

Macro HQ region for an organization — MENA, GCC, Europe, North America, ...
One level *above* `organizations.hq_country`, and deliberately distinct from
`organizations.geographic_focus`, which records where an org *invests* rather
than where it sits.

Populated by tooling writing into Attio `organizations.region` (added in the
same change, see `crm-sync/scripts/source-attio/_internal/schema.ps1`), then
mirrored down by the webhook/nightly sync. It has no SOURCE Attio counterpart,
so there is no `source-to-target-mapping.json` entry and the migration
backfills nothing — existing rows stay NULL until a tool writes them.

Plain nullable text with no CHECK constraint or enum: free-form by decision
(2026-09-12), matching `hq_country`'s existing shape.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against).

Revision ID: c7e3a95d2f18
Revises: f5cd5212e82e
Create Date: 2026-09-12 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7e3a95d2f18"
down_revision: str | Sequence[str] | None = "f5cd5212e82e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("organizations", sa.Column("region", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("organizations", "region")
