"""create feedback_submissions table (2026-09-14)

Durable record of in-app feedback pushed by the WusoolScribe desktop app
(`POST /desktop/feedback`, `meetings` module). The row is written first and
is the source of truth; a best-effort SES email notification follows and
does not gate the response -- `email_sent`/`email_sent_at` exist so that a
failed notification stays visible (queryable) instead of silently vanishing.

Hand-written, not autogenerated (no live DB connection in this session).

Revision ID: d3f49e19fd35
Revises: c7e3a95d2f18
Create Date: 2026-09-14 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3f49e19fd35"
down_revision: str | Sequence[str] | None = "c7e3a95d2f18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "feedback_submissions",
        sa.Column(
            "id",
            postgresql.UUID(),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("contact", sa.Text(), nullable=True),
        sa.Column("install_id", sa.Text(), nullable=False),
        sa.Column("app_version", sa.Text(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column(
            "email_sent", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("email_sent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "category IN ('bug','feature_request','transcription_quality','other')",
            name="feedback_submissions_category_check",
        ),
    )
    op.create_index(
        "idx_feedback_submissions_created_at",
        "feedback_submissions",
        [sa.text("created_at DESC")],
    )
    op.create_index(
        "idx_feedback_submissions_install_id", "feedback_submissions", ["install_id"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("idx_feedback_submissions_install_id", table_name="feedback_submissions")
    op.drop_index("idx_feedback_submissions_created_at", table_name="feedback_submissions")
    op.drop_table("feedback_submissions")
