"""rename deals.estimated_deal_value_aed to estimated_deal_value_usd (2026-08-25)

AED -> USD cleanup: every currency-related column/attribute default across
Buyer Role, Seller Role, and Deal moves from AED to USD (schema.ps1,
money.py, Slack field-spec labels). Deal's `estimated_deal_value_aed` is a
plain number (not a currency-typed field, per f3a8c1d92b47's note), so
there's no currency code to flip -- the field itself is renamed instead,
matching the DEV Attio attribute rename (schema.ps1's `RenameFrom`).

Pure rename, no data transform -- the underlying numbers are not
recalculated. If the historical values were actually entered in AED, they
now read as an equivalent-looking USD number under the renamed column;
converting the historical figures themselves was explicitly out of scope
for this cleanup.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against).

Revision ID: d4e6b7a91c53
Revises: c1a9f4e83d67
Create Date: 2026-08-25 00:00:00.000000

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4e6b7a91c53"
down_revision: str | Sequence[str] | None = "c1a9f4e83d67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column("deals", "estimated_deal_value_aed", new_column_name="estimated_deal_value_usd")


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column("deals", "estimated_deal_value_usd", new_column_name="estimated_deal_value_aed")
