"""extensions, enum types, and the scribe_pub placeholder role

Hand-written baseline revision — everything an empty database needs *before*
any `CREATE TABLE` can run, none of which `alembic revision --autogenerate`
can produce on its own:

  1. Extensions (mirrors database/sql/001_extensions.sql exactly): pgcrypto,
     pg_trgm, and a guarded pgvector (some Postgres images don't ship the
     pgvector shared library at all, so that one must not hard-fail).

  2. The three native Postgres enum types consumed by `meetings`
     (database/sql/005_meetings.sql): meeting_source, counterparty_role,
     meeting_type. app.models.meeting deliberately declares these with
     `create_type=False` (see that module's docstring and
     ALEMBIC_MIGRATION_HANDOVER.md point 4) because this revision already
     owns CREATE TYPE for them. `create_type=False` means the autogenerated
     `CREATE TABLE meetings` in the next revision will never emit `CREATE
     TYPE`, so these must exist before that revision runs or `alembic upgrade
     head` fails outright on an empty database. Do NOT flip `create_type` on
     the model to "fix" this — integration tests run against a real
     alembic-migrated database (see checks.sh), not `metadata.create_all()`,
     so flipping it would instead make autogenerate try to re-emit `CREATE
     TYPE` for types this revision already created.

  3. The `scribe_pub` role (placeholder only — see next revision for its
     GRANTs).

     *** SECURITY NOTE — READ BEFORE TOUCHING THIS ***

     database/sql/005_meetings.sql documents (but does NOT execute) a real
     `CREATE ROLE scribe_pub LOGIN PASSWORD '<generate-a-strong-one>'` for a
     human to run once, by hand, with a real generated password. That
     statement is deliberately commented out in the .sql file and must NEVER
     be replayed here with a literal password — doing so would commit a
     fake-but-real-looking, permanently-public (via git history) credential
     for a role with write access to `meetings` and read access to
     `organizations`. Any database that already has the real `scribe_pub`
     role (every dev/prod environment that matters) must have this
     migration be a complete no-op against that role.

     So: this migration creates `scribe_pub` as NOLOGIN — a harmless
     placeholder with no password and no ability to authenticate — and only
     if the role does not already exist. On any real environment the actual
     LOGIN role with its real password already exists, so the `IF NOT
     EXISTS` guard skips role creation entirely and the real role/password
     is never read, written, or touched.

     The GRANTs themselves live in a later revision
     (grant_scribe_pub_privileges), not this one, because they target
     `meetings` and `organizations`, which do not exist until the
     autogenerated table-creation revision after this one runs. See that
     revision's docstring for the rest of this reasoning — read both before
     changing either.

     If you are here to "fix" this because it looks incomplete: it is not
     missing a password, it is intentionally never supposed to have one in
     this file. The real password lives only in whatever secret store the
     human who ran the real `CREATE ROLE` used — never in source control.

Revision ID: d982478fc6e3
Revises:
Create Date: 2026-08-18 00:17:04.922539

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d982478fc6e3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- 1. Extensions (database/sql/001_extensions.sql, verbatim) --------
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute(
        """
        DO $$
        BEGIN
          CREATE EXTENSION IF NOT EXISTS vector;
        EXCEPTION
          WHEN undefined_file THEN
            RAISE NOTICE 'pgvector extension is not installed on this PostgreSQL server; vector columns will be created after pgvector is available.';
        END
        $$;
        """
    )

    # --- 2. Enum types consumed by `meetings` (create_type=False on the
    #        model — see module docstring above) ---------------------------
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'meeting_source') THEN
            CREATE TYPE meeting_source AS ENUM ('in_house', 'granola', 'manual');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'counterparty_role') THEN
            CREATE TYPE counterparty_role AS ENUM ('buyer', 'seller');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'meeting_type') THEN
            CREATE TYPE meeting_type AS ENUM (
                'enrichment',
                'alignment',
                'owner_iv',
                'buyer_intro',
                'internal'
            );
          END IF;
        END
        $$;
        """
    )

    # --- 3. scribe_pub placeholder role — see the SECURITY NOTE above
    #        before changing anything in this block. Grants are added by a
    #        later revision, once `meetings`/`organizations` exist. --------
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'scribe_pub') THEN
            CREATE ROLE scribe_pub NOLOGIN;
          END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    """Downgrade schema.

    Deliberately does NOT drop the pgcrypto/pg_trgm/vector extensions or the
    scribe_pub role: extensions are shared, low-cost infrastructure that
    other objects may depend on, and scribe_pub may be the real (human
    provisioned, LOGIN) role in any environment where this was a no-op on
    upgrade — unconditionally dropping it here would destroy a real
    production role from a migration file that never created it. Dropping
    the enum types (only usable by `meetings`, dropped by the revision
    below this one on the way down) is safe and reversible.
    """
    op.execute("DROP TYPE IF EXISTS meeting_type;")
    op.execute("DROP TYPE IF EXISTS counterparty_role;")
    op.execute("DROP TYPE IF EXISTS meeting_source;")
