"""add organizations.lead_source_detail (2026-09-15)

Which lead-magnet a company arrived through -- Valuation Tool, M&A Readiness
Tool, Buyer Form, or GCC SME Benchmark.

This is the detail `organizations.lead_source` deliberately does not carry:
that field is a two-option Inbound/Outbound classification, and the SOURCE->V2
migration writes every organization as "Inbound" (`crm-sync/scripts/
source-attio/_internal/objects.ps1`). SOURCE Attio's own `companies.lead_source`
has always held the tool name, but it was absent from that script's field-
mapping table, so no code in this repo ever read it -- the tool name was never
lost in translation, it was never fetched. Both
`crm-sync/scripts/source-attio/config/target-schema.json` and
`source-to-target-mapping.json` already described this design; neither is read
at runtime.

Plain nullable text, no CHECK or enum, matching `lead_source`'s own shape --
the controlled vocabulary lives in Attio's select options, which are copied
from SOURCE rather than restated here (see `_internal/schema.ps1`).

Single-valued even though SOURCE's attribute is a multiselect: one company
(Arto) genuinely holds two tools 16 minutes apart, and `objects.ps1`'s
`Get-LatestLeadSourceDetail` collapses them to the most recent `active_from`,
mirroring the existing `Get-NormalizedRelationshipStatus` rule.

No backfill. Values arrive from Attio through the webhook and nightly syncs
once the attribute is populated there; existing rows stay NULL until then.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against).

Revision ID: e1f7a3c95b28
Revises: b8c41e7d09a2
Create Date: 2026-09-15 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1f7a3c95b28"
down_revision: str | Sequence[str] | None = "b8c41e7d09a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("organizations", sa.Column("lead_source_detail", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("organizations", "lead_source_detail")
