"""add notes.attio_id (2026-09-16)

The origin marker `notes` has never had, and the reason notes are the one
mirrored table deletion reconciliation cannot safely touch.

`notes.id` does double duty today. When the meetings pipeline pushes a note to
Attio successfully, `meetings/persistence/notes_repository.py` reuses Attio's
record id as the primary key. When that push fails,
`meetings/application/publish.py` sets `note_attio_id = None` and the column's
own `gen_random_uuid()` default applies instead. Both are UUIDs, and nothing on
the row says which kind it is.

A set-difference against Attio therefore cannot tell a note deleted in Attio
from a meeting summary that only ever existed here -- and stamping the latter
`removed_at` would silently hide a transcript summary that exists nowhere else.
So `notes` was excluded from reconciliation entirely.

This column makes the distinction explicit: non-NULL means the note came from
(or reached) Attio and may be reconciled against it; NULL means locally
authored and must never be, which the reconciliation gets for free because
`NULL = ANY(...)` is never true.

Nullable and UNIQUE, matching how `buyer_roles.legacy_entry_id` identifies an
Attio-derived row. No backfill here: populating it correctly requires reading
the live Attio note list, so it is done by
`server/scripts/postgres-sync/prod/backfill-notes-attio-id.py`, which only sets
the column for ids Attio actually returns. Doing it in SQL as
`attio_id = id` would be wrong the moment a single failed-push note exists --
it would mark a Postgres-only note as Attio-derived and hand it straight to the
reconciliation that this column exists to protect it from.

Verified in prod on 2026-09-16 before writing this: all 394 note ids match
Attio's 394 exactly, so the backfill is currently unambiguous for every row.
That will stop being true as soon as one push fails, which is why it is worth
doing now.

Hand-written, not autogenerated.

Revision ID: f2b8d1c47e93
Revises: e1f7a3c95b28
Create Date: 2026-09-16 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2b8d1c47e93"
down_revision: str | Sequence[str] | None = "e1f7a3c95b28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("notes", sa.Column("attio_id", sa.Text(), nullable=True))
    op.create_unique_constraint("notes_attio_id_key", "notes", ["attio_id"])


def downgrade() -> None:
    op.drop_constraint("notes_attio_id_key", "notes", type_="unique")
    op.drop_column("notes", "attio_id")
