"""add Attio schema handover field expansions (2026-08-19)

Adds the columns decided in the "Wusool Schema Handover" artifact and wired
into `workflows/crm-sync/scripts/_internal/{objects,lists}.ps1` on 2026-08-19:
social/profile fields on Organization and Person, Deal's NDA/advisor/close
fields, Mandate's sellers_interested/retainer_amount, and Buyer Role's
expanded requirement-profile fields.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against) -- types were confirmed against the real DEV Attio
attributes via the API rather than assumed from the ER diagram, which
mislabels `typical_check_size` as a scalar money field when it is actually a
multiselect (see `buyer_roles.typical_check_size` below), and mislabels
`Deal.estimated_deal_value_aed` as currency when the real DEV attribute type
is a plain number.

`Organization.employee_range` from the diagram is intentionally not included
here -- that DEV Attio attribute does not exist yet (blocked on reconciling
SOURCE's bands with the requested target bands; see
`source-to-target-mapping.json`).

Revision ID: f3a8c1d92b47
Revises: 6b0642671e13
Create Date: 2026-08-19 07:05:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a8c1d92b47"
down_revision: str | Sequence[str] | None = "6b0642671e13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("organizations", sa.Column("angellist", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("facebook", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("instagram", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("twitter", sa.Text(), nullable=True))
    op.add_column(
        "organizations", sa.Column("twitter_follower_count", sa.Integer(), nullable=True)
    )
    op.add_column("organizations", sa.Column("foundation_date", sa.Date(), nullable=True))
    op.add_column("organizations", sa.Column("ticket_size", sa.Text(), nullable=True))
    op.add_column("organizations", sa.Column("lead_source", sa.Text(), nullable=True))

    op.add_column("people", sa.Column("job_title", sa.Text(), nullable=True))
    op.add_column("people", sa.Column("contact_type", sa.Text(), nullable=True))
    op.add_column("people", sa.Column("phone", sa.Text(), nullable=True))
    op.add_column("people", sa.Column("avatar_url", sa.Text(), nullable=True))
    op.add_column("people", sa.Column("angellist", sa.Text(), nullable=True))
    op.add_column("people", sa.Column("facebook", sa.Text(), nullable=True))
    op.add_column("people", sa.Column("instagram", sa.Text(), nullable=True))
    op.add_column("people", sa.Column("twitter", sa.Text(), nullable=True))
    op.add_column("people", sa.Column("twitter_follower_count", sa.Integer(), nullable=True))

    op.add_column("deals", sa.Column("nda_status", sa.Text(), nullable=True))
    op.add_column(
        "deals", sa.Column("estimated_deal_value_aed", sa.Numeric(), nullable=True)
    )
    op.add_column("deals", sa.Column("expected_close_date", sa.Date(), nullable=True))
    op.add_column("deals", sa.Column("fee", sa.Numeric(), nullable=True))
    op.add_column(
        "deals",
        sa.Column(
            "assigned_advisor",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )

    op.add_column("mandates", sa.Column("sellers_interested", sa.Integer(), nullable=True))
    op.add_column(
        "mandates",
        sa.Column("retainer_amount", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )

    op.add_column(
        "buyer_roles",
        sa.Column("ebitda_ceiling", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "buyer_roles",
        sa.Column("estimated_aum", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("buyer_roles", sa.Column("mandate_details", sa.Text(), nullable=True))
    op.add_column("buyer_roles", sa.Column("notable_investments", sa.Text(), nullable=True))
    op.add_column("buyer_roles", sa.Column("key_personnel", sa.Text(), nullable=True))
    op.add_column("buyer_roles", sa.Column("relationship_warmth", sa.Text(), nullable=True))
    op.add_column(
        "buyer_roles",
        sa.Column(
            "target_geography",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "buyer_roles",
        sa.Column(
            "typical_check_size",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "buyer_roles", sa.Column("last_mandate_briefing_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "buyer_roles", sa.Column("prior_gcc_acquisition", sa.Text(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("buyer_roles", "prior_gcc_acquisition")
    op.drop_column("buyer_roles", "last_mandate_briefing_date")
    op.drop_column("buyer_roles", "typical_check_size")
    op.drop_column("buyer_roles", "target_geography")
    op.drop_column("buyer_roles", "relationship_warmth")
    op.drop_column("buyer_roles", "key_personnel")
    op.drop_column("buyer_roles", "notable_investments")
    op.drop_column("buyer_roles", "mandate_details")
    op.drop_column("buyer_roles", "estimated_aum")
    op.drop_column("buyer_roles", "ebitda_ceiling")

    op.drop_column("mandates", "retainer_amount")
    op.drop_column("mandates", "sellers_interested")

    op.drop_column("deals", "assigned_advisor")
    op.drop_column("deals", "fee")
    op.drop_column("deals", "expected_close_date")
    op.drop_column("deals", "estimated_deal_value_aed")
    op.drop_column("deals", "nda_status")

    op.drop_column("people", "twitter_follower_count")
    op.drop_column("people", "twitter")
    op.drop_column("people", "instagram")
    op.drop_column("people", "facebook")
    op.drop_column("people", "angellist")
    op.drop_column("people", "avatar_url")
    op.drop_column("people", "phone")
    op.drop_column("people", "contact_type")
    op.drop_column("people", "job_title")

    op.drop_column("organizations", "lead_source")
    op.drop_column("organizations", "ticket_size")
    op.drop_column("organizations", "foundation_date")
    op.drop_column("organizations", "twitter_follower_count")
    op.drop_column("organizations", "twitter")
    op.drop_column("organizations", "instagram")
    op.drop_column("organizations", "facebook")
    op.drop_column("organizations", "angellist")
