"""add seller_roles lead-magnet output columns and the tool_runs ledger (2026-09-06)

Two changes, both from the lead-magnet field audit and Raoof's review of it.

1. `seller_roles` gains the 26 fields the four lead-magnet tools compute but
   had nowhere to put. Until now those were written only to the legacy
   `lead_magnet_inbound_benchmark`/`lead_magnet_inbound` Attio lists, which
   the Postgres mirror does not read -- so none of it reached this database.
   The matching Attio attributes were created on the SOURCE workspace the
   same day via `source-attio/ensure-schema.ps1`.

   The nine `pct_*` rankings are discrete columns rather than one JSONB blob
   so they stay filterable; that queryability is the whole reason they are
   real columns instead of `organizations.raw_attio`, which the nightly
   resync overwrites wholesale on every run.

   Money columns follow the existing `{"amount": ..., "currency": ...}` JSONB
   shape and are USD, matching every V2 Attio currency attribute.

2. `tool_runs`, a Postgres-only ledger of tool invocations, plus
   `activities.tool_run_id` linking a timeline row to the run behind it.
   `activities` keeps its human-interaction role unchanged; runs need their
   own table because `activities_subject_present` makes it impossible to
   record a submission that failed before any subject record existed -- which
   is exactly the lead-loss case the ledger exists to catch.

`is_test` is deliberately NOT here: the dev/prod discriminator lives only in
Attio and is applied as a sync-time filter, not stored per row.

Hand-written, not autogenerated (no live DB connection in this session).

Revision ID: f7a2c9e14b83
Revises: 2565f7950641
Create Date: 2026-09-06 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7a2c9e14b83"
down_revision: str | Sequence[str] | None = "2565f7950641"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_NUMERIC_COLS = (
    "benchmark_score",
    "pct_ebitda_margin",
    "pct_revenue_growth",
    "pct_revenue_per_employee",
    "pct_concentration",
    "pct_gross_margin",
    "pct_premises_cost",
    "pct_recurring_revenue",
    "pct_capital_efficiency",
    "pct_revenue_scale",
)
_TEXT_COLS = (
    "benchmark_band",
    "benchmark_quartile",
    "lead_priority",
    "routing_reason",
    "quality_check",
    "benchmark_review",
    "review_note",
    "headline_flag",
    "recommended_referral",
)
_JSONB_COLS = ("implied_ev_low", "implied_ev_high", "ebitda_adjusted")
_INT_COLS = ("headcount", "days_to_get_paid")
_BOOL_COLS = ("data_consent", "include_in_benchmark")


def upgrade() -> None:
    """Upgrade schema."""
    for name in _NUMERIC_COLS:
        op.add_column("seller_roles", sa.Column(name, sa.Numeric(), nullable=True))
    for name in _TEXT_COLS:
        op.add_column("seller_roles", sa.Column(name, sa.Text(), nullable=True))
    for name in _JSONB_COLS:
        op.add_column(
            "seller_roles",
            sa.Column(name, postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        )
    for name in _INT_COLS:
        op.add_column("seller_roles", sa.Column(name, sa.Integer(), nullable=True))
    for name in _BOOL_COLS:
        op.add_column("seller_roles", sa.Column(name, sa.Boolean(), nullable=True))

    op.create_table(
        "tool_runs",
        sa.Column(
            "id",
            postgresql.UUID(),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tool", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True, unique=True),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        # Every subject nullable and no CHECK requiring one -- see the module
        # docstring on app/models/tool_run.py.
        sa.Column(
            "organization_attio_id",
            sa.Text(),
            sa.ForeignKey("organizations.attio_id"),
            nullable=True,
        ),
        sa.Column(
            "person_attio_id", sa.Text(), sa.ForeignKey("person.attio_id"), nullable=True
        ),
        sa.Column(
            "seller_role_id",
            postgresql.UUID(),
            sa.ForeignKey("seller_roles.id"),
            nullable=True,
        ),
        sa.Column(
            "buyer_role_id",
            postgresql.UUID(),
            sa.ForeignKey("buyer_roles.id"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "status IN ('running','succeeded','failed','abandoned')",
            name="tool_runs_status_check",
        ),
    )
    op.create_index("idx_tool_runs_tool", "tool_runs", ["tool"])
    op.create_index("idx_tool_runs_status", "tool_runs", ["status"])
    op.create_index("idx_tool_runs_started_at", "tool_runs", [sa.text("started_at DESC")])
    op.create_index("idx_tool_runs_organization", "tool_runs", ["organization_attio_id"])

    op.add_column("activities", sa.Column("tool_run_id", postgresql.UUID(), nullable=True))
    op.create_foreign_key(
        "activities_tool_run_id_fkey", "activities", "tool_runs", ["tool_run_id"], ["id"]
    )
    op.create_index("idx_activities_tool_run", "activities", ["tool_run_id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("idx_activities_tool_run", table_name="activities")
    op.drop_constraint("activities_tool_run_id_fkey", "activities", type_="foreignkey")
    op.drop_column("activities", "tool_run_id")

    op.drop_index("idx_tool_runs_organization", table_name="tool_runs")
    op.drop_index("idx_tool_runs_started_at", table_name="tool_runs")
    op.drop_index("idx_tool_runs_status", table_name="tool_runs")
    op.drop_index("idx_tool_runs_tool", table_name="tool_runs")
    op.drop_table("tool_runs")

    for name in reversed(_BOOL_COLS + _INT_COLS + _JSONB_COLS + _TEXT_COLS + _NUMERIC_COLS):
        op.drop_column("seller_roles", name)
