"""Serves the four tool pages and `embed.js`.

Headers live here rather than in the Caddyfile because that file is
generated by a Terraform template that loops over every app — a `header`
directive there would also apply to the Slack bot's vhost.

No CORS middleware, deliberately. `embed.js` builds an iframe whose `src` is
on this host, so the tool document's own `fetch` calls back to this same
host (e.g. `POST /benchmark`) are same-origin: there is no preflight and no
`Access-Control-Allow-Origin` to set. Adding one would be dead config.
"""

from pathlib import Path

from starlette.responses import Response
from starlette.staticfiles import StaticFiles
from starlette.types import Scope

from app.modules.lead_magnets.config import get_settings

_STATIC_DIR = Path(__file__).resolve().parent.parent / "static"

# Content-addressed under img/ (`<sha8>.<ext>`), so the name changes whenever
# the bytes do and a year is safe. Everything else is short: `embed.js` is
# both the cutover switch and the rollback switch, and a long TTL there is
# how a rollback takes an hour instead of a minute.
_IMMUTABLE = "public, max-age=31536000, immutable"
_SHORT = "public, max-age=60"


def static_dir() -> Path:
    """Resolved relative to this file, never to the working directory: in the
    container these files live under `.venv/.../site-packages/app/...` while
    `WORKDIR` is `/app`.
    """
    return _STATIC_DIR


class ToolStatic(StaticFiles):
    async def get_response(self, path: str, scope: Scope) -> Response:
        response = await super().get_response(path, scope)
        # frame-ancestors, and no `X-Frame-Options`: XFO has no working
        # allow-list value, so setting it at all would block the Webflow
        # embed outright.
        response.headers["Content-Security-Policy"] = (
            f"frame-ancestors {get_settings().lead_magnet_frame_ancestors}"
        )
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["Cache-Control"] = _IMMUTABLE if path.startswith("img/") else _SHORT
        return response
