"""drop mandates and mandate_targets tables (2026-08-23)

The DEV Attio Mandates list itself is fully retired: every entry was
one-time migrated into its own Deal record (`deal_type` set directly, see
`9c4d71ea2b56`). Its 2 historical rows in `mandates` add nothing that isn't
now on the corresponding `deals` rows, and `mandate_targets` was never
populated in the first place (`mandate_target.py`'s own docstring: "not
mapped in this phase -- no repository or test needs it yet"). Nothing in
`wusool-toolkit` (`matching-engine` or `ddl-commands`) imports the `Mandate`
or `MandateTarget` model classes directly -- checked before writing this --
so this is safe against the live application, not just the CRM-sync
scripts. `-MigrateMandates` (Attio-side, in
`workflows/crm-sync/scripts/_internal/objects.ps1`) is unaffected: it reads
the live DEV Attio Mandates list directly via the API, never this table.

Order matters: `seller_roles.mandate_id` and `mandate_targets.mandate_id`
both FK to `mandates.id`, so both must go before `mandates` itself.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against), following the same precedent as `f3a8c1d92b47`,
`9c4d71ea2b56`, and `7b3f0d5e9a41`.

Revision ID: 2e8a6c14f7b9
Revises: 7b3f0d5e9a41
Create Date: 2026-08-23 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e8a6c14f7b9"
down_revision: str | Sequence[str] | None = "7b3f0d5e9a41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("seller_roles", "mandate_id")
    op.drop_table("mandate_targets")
    op.drop_table("mandates")


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table(
        "mandates",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("attio_id", sa.Text(), nullable=True),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("buyer_attio_id", sa.Text(), nullable=True),
        sa.Column("seller_attio_id", sa.Text(), nullable=True),
        sa.Column("phase", sa.Text(), nullable=True),
        sa.Column("assigned_advisor_attio_ids", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("universe_constructed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("shortlist_approved", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("universe_size", sa.Integer(), nullable=True),
        sa.Column("shortlist_size", sa.Integer(), nullable=True),
        sa.Column("tier1_contacted", sa.Integer(), nullable=True),
        sa.Column("responses", sa.Integer(), nullable=True),
        sa.Column("sellers_interested", sa.Integer(), nullable=True),
        sa.Column("retainer_amount", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_attio", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["buyer_attio_id"], ["organizations.attio_id"]),
        sa.ForeignKeyConstraint(["seller_attio_id"], ["organizations.attio_id"]),
        sa.UniqueConstraint("attio_id"),
    )
    op.create_table(
        "mandate_targets",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("mandate_id", postgresql.UUID(), nullable=False),
        sa.Column("seller_attio_id", sa.Text(), nullable=False),
        sa.Column("proxy_size", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("tier", sa.Text(), nullable=True),
        sa.Column("score", sa.Numeric(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["mandate_id"], ["mandates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seller_attio_id"], ["organizations.attio_id"], ondelete="CASCADE"),
        sa.UniqueConstraint("mandate_id", "seller_attio_id", name="mandate_targets_mandate_id_seller_attio_id_key"),
    )
    op.add_column("seller_roles", sa.Column("mandate_id", postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, "seller_roles", "mandates", ["mandate_id"], ["id"])
