"""drop buyer_roles.typical_check_size (2026-08-23)

Redundant with the existing `buyer_roles.check_size_min`/`check_size_max`
columns -- `typical_check_size` was a coarse 4-option USD range bucket
(`Under $1M` / `$1-5M` / `$5-20M` / `$20M+`), while check_size_min/max are
real, more-precise AED figures. Before this column was dropped,
`_internal/lists.ps1`'s `Invoke-BuyerRole` backfilled check_size_min/max
from it wherever SOURCE left those blank (never overwriting an
already-resolved real value), converted at the USD/AED peg (1 USD = 3.6725
AED). That backfill logic still reads SOURCE's `typical_check_size_7`
directly -- only the DEV-side `typical_check_size` column (and its Attio
attribute, archived, not hard-deleted -- Attio doesn't support that) is
gone. See `workflows/crm-sync/scripts/config/migration-decisions.json`'s
`dropped_fields.buyer_role.typical_check_size`.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against), following the same precedent as `f3a8c1d92b47`,
`9c4d71ea2b56`, `7b3f0d5e9a41`, and `2e8a6c14f7b9`.

Revision ID: a4f9e61c3d78
Revises: 2e8a6c14f7b9
Create Date: 2026-08-23 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4f9e61c3d78"
down_revision: str | Sequence[str] | None = "2e8a6c14f7b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("buyer_roles", "typical_check_size")


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column(
        "buyer_roles",
        sa.Column(
            "typical_check_size",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
