"""allow multiple buyer_roles/seller_roles per organization (2026-08-28)

Moves the UNIQUE constraint from `org_attio_id` to `legacy_entry_id` on both
`buyer_roles` and `seller_roles`. Until now, `sync-postgres.ps1` filtered out
every DEV Attio `buyer_role`/`seller_role` list entry except the currently
active one before writing to Postgres, specifically so the one-row-per-org
UNIQUE(org_attio_id) constraint would hold. Per explicit product decision,
Postgres should mirror every DEV Attio entry -- `is_active` is how a caller
tells the current entry apart from stale duplicates, not something the sync
script pre-filters on. See `wusool_db/models/buyer_role.py`'s docstring.

`org_attio_id` keeps a plain (non-unique) index for lookup performance;
`legacy_entry_id` becomes the new UNIQUE key (one row per DEV entry).
Postgres already allows multiple NULLs in a UNIQUE column, so this doesn't
block any row that genuinely has no legacy_entry_id.

The original UNIQUE(org_attio_id) constraints were created inline in
`003_crm_roles.sql`'s `CREATE TABLE` statements with no explicit name, so
Postgres auto-named them using its default `<table>_<column>_key` pattern.
Dropped via a dynamic pg_constraint lookup rather than hardcoding that name,
in case it turns out different on the live database -- no live DB
connection available in this session to confirm directly.

Hand-written, not autogenerated (no live DB connection available in this
session).

Revision ID: b8f4c1e93a56
Revises: d4e6b7a91c53
Create Date: 2026-08-28 19:45:00.000000

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8f4c1e93a56"
down_revision: str | Sequence[str] | None = "d4e6b7a91c53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DROP_ORG_UNIQUE_SQL = """
DO $$
DECLARE
    constraint_name text;
BEGIN
    SELECT conname INTO constraint_name
    FROM pg_constraint
    WHERE conrelid = '{table}'::regclass AND contype = 'u'
      AND conkey = (SELECT array_agg(attnum) FROM pg_attribute
                    WHERE attrelid = '{table}'::regclass AND attname = 'org_attio_id');
    IF constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE {table} DROP CONSTRAINT %I', constraint_name);
    END IF;
END
$$;
"""


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(_DROP_ORG_UNIQUE_SQL.format(table="buyer_roles"))
    op.execute(_DROP_ORG_UNIQUE_SQL.format(table="seller_roles"))
    op.create_index("idx_buyer_roles_org_attio_id", "buyer_roles", ["org_attio_id"])
    op.create_index("idx_seller_roles_org_attio_id", "seller_roles", ["org_attio_id"])
    op.create_unique_constraint("buyer_roles_legacy_entry_id_key", "buyer_roles", ["legacy_entry_id"])
    op.create_unique_constraint("seller_roles_legacy_entry_id_key", "seller_roles", ["legacy_entry_id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("seller_roles_legacy_entry_id_key", "seller_roles", type_="unique")
    op.drop_constraint("buyer_roles_legacy_entry_id_key", "buyer_roles", type_="unique")
    op.drop_index("idx_seller_roles_org_attio_id", table_name="seller_roles")
    op.drop_index("idx_buyer_roles_org_attio_id", table_name="buyer_roles")
    op.create_unique_constraint("seller_roles_org_attio_id_key", "seller_roles", ["org_attio_id"])
    op.create_unique_constraint("buyer_roles_org_attio_id_key", "buyer_roles", ["org_attio_id"])
