"""add seller_roles lead magnet fields (2026-08-25)

Adds the fields from the Lead Magnet questionnaire (Slack, 2026-08-24) that
had no existing home on `seller_roles` or `organizations`: `years_active`,
`funding_stage`, `revenue_last_full_year`, `revenue_year_before`,
`gross_margin_pct`, `ebitda_deducts_salary`, `annual_rent_cost`,
`largest_customer_revenue_pct`, `repeat_revenue_pct`, `location_count`.

Sector, geography, EBITDA, and total raised already exist
(`organizations.sector_focus`/`geographic_focus`, `seller_roles.est_ebitda`,
`organizations.funding_raised`) and are not duplicated here. Headcount is
also skipped -- `organizations.employee_range` already covers it.

Money fields follow the existing `{"amount": ..., "currency": ...}` JSONB
shape used by `est_revenue`/`est_ebitda`/`owner_salary` so both AED (Tech)
and USD (Traditional) submissions can be stored without a schema branch.

Hand-written, not autogenerated (no live DB connection available in this
session to diff against).

Revision ID: c1a9f4e83d67
Revises: b7c2e419d5a3
Create Date: 2026-08-25 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1a9f4e83d67"
down_revision: str | Sequence[str] | None = "b7c2e419d5a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("seller_roles", sa.Column("years_active", sa.Integer(), nullable=True))
    op.add_column("seller_roles", sa.Column("funding_stage", sa.Text(), nullable=True))
    op.add_column(
        "seller_roles",
        sa.Column(
            "revenue_last_full_year", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "seller_roles",
        sa.Column("revenue_year_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("seller_roles", sa.Column("gross_margin_pct", sa.Numeric(), nullable=True))
    op.add_column(
        "seller_roles", sa.Column("ebitda_deducts_salary", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "seller_roles",
        sa.Column("annual_rent_cost", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "seller_roles", sa.Column("largest_customer_revenue_pct", sa.Numeric(), nullable=True)
    )
    op.add_column("seller_roles", sa.Column("repeat_revenue_pct", sa.Numeric(), nullable=True))
    op.add_column("seller_roles", sa.Column("location_count", sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("seller_roles", "location_count")
    op.drop_column("seller_roles", "repeat_revenue_pct")
    op.drop_column("seller_roles", "largest_customer_revenue_pct")
    op.drop_column("seller_roles", "annual_rent_cost")
    op.drop_column("seller_roles", "ebitda_deducts_salary")
    op.drop_column("seller_roles", "gross_margin_pct")
    op.drop_column("seller_roles", "revenue_year_before")
    op.drop_column("seller_roles", "revenue_last_full_year")
    op.drop_column("seller_roles", "funding_stage")
    op.drop_column("seller_roles", "years_active")
