"""add organizations.logo_url and buyer/seller_roles.is_active/legacy_entry_id (2026-08-19)

Direct 1:1 mirrors of DEV Attio columns of the same name, no transform:

- `organizations.logo_url` -- plain text URL, same shape as `linkedin`.
- `buyer_roles.is_active` / `legacy_entry_id` and `seller_roles.is_active` /
  `legacy_entry_id` -- mirror the Buyer/Seller Database `is_active` flag and
  `legacy_entry_id` field added when duplicate SOURCE submissions were split
  into separate DEV entries instead of being blended (see the Wusool Schema
  Handover artifact). sync-postgres.ps1 only ever writes the active entry
  per organization, so `is_active` will always read true here -- it's kept
  for parity with DEV Attio's schema rather than as a live filter in
  Postgres. `legacy_entry_id` records which exact DEV list entry the row
  came from.

Hand-written, not autogenerated (no live DB connection available in this
session).

Revision ID: e5b1c9a2f60d
Revises: d3a97c6b8e42
Create Date: 2026-08-19 16:30:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5b1c9a2f60d"
down_revision: str | Sequence[str] | None = "d3a97c6b8e42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("organizations", sa.Column("logo_url", sa.Text(), nullable=True))
    op.add_column("buyer_roles", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("buyer_roles", sa.Column("legacy_entry_id", sa.Text(), nullable=True))
    op.add_column("seller_roles", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("seller_roles", sa.Column("legacy_entry_id", sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("seller_roles", "legacy_entry_id")
    op.drop_column("seller_roles", "is_active")
    op.drop_column("buyer_roles", "legacy_entry_id")
    op.drop_column("buyer_roles", "is_active")
    op.drop_column("organizations", "logo_url")
