"""The live `organizations.sector_focus` option titles — generated.

Extracted from `ddl_commands/api/organizations.py`'s `FieldSpec`, which is
this repo's authoritative copy of the workspace's own select options and is
already covered by `test_field_specs_match_attio_registries.py`. Duplicated
here rather than imported so `domain/` does not reach into another module's
`api/` layer, and regenerated from that spec if the option set changes.

Used to validate every mapping target at import: Attio rejects an undefined
select value and the live relay only logs it, so a typo would silently drop
the sector on every write.
"""

SECTOR_FOCUS_OPTIONS: frozenset[str] = frozenset(
    {
        "Clinic",
        "Garage",
        "Legal Services",
        "Retail / E-Commerce",
        "Utilities",
        "Creative / Arts & Culture",
        "IT Services / Distribution",
        "Industrial Manufacturing",
        "Pharmaceuticals / Biotech",
        "Trade & Technical Services",
        "Packaging & Materials",
        "Telecom / Connectivity",
        "Residential / Commercial Real Estate",
        "Cybersecurity",
        "Sports & Wellness",
        "Beauty & Personal Care",
        "EdTech / Education",
        "Diversified / Generalist",
        "Steel / Metals / Mining",
        "Oil & Gas",
        "Impact / ESG / Sustainability",
        "Fintech",
        "Asset Management",
        "Agriculture / AgriTech",
        "Technology",
        "Logistics / 3PL / Freight",
        "Enterprise Software",
        "Banking / Commercial",
        "AI / ML",
        "Construction & Engineering",
        "Luxury / Fashion / Apparel",
        "Gaming / Metaverse",
        "Real Assets",
        "Dental / Specialist Clinics",
        "Private Credit / Debt",
        "Web3 / Blockchain / Digital Assets",
        "Energy Infrastructure",
        "Food Manufacturing / FoodTech",
        "Public Markets / Equities",
        "Aviation / Aircraft Leasing",
        "Chemicals & Petrochemicals",
        "Medical Education",
        "B2B Business Services",
        "Biotech / Longevity",
        "FemTech / Mental Health",
        "Electrical Equipment",
        "Medical Devices & Supplies",
        "HR / Human Capital",
        "Healthcare Services / Clinics",
        "Supply Chain / Distribution",
        "SaaS / Cloud",
        "Property Management / Proptech",
        "Private Equity",
        "Healthtech / Digital Health",
        "Renewable Energy / CleanTech",
        "FMCG / Consumer Goods",
        "Venture / Growth (Africa / MENA SME)",
        "Space / Deep Tech",
        "Media / Entertainment / Gaming",
        "Family Office / Wealth Management",
        "Consulting / Advisory",
        "Marketing / AdTech",
        "Venture Capital",
        "Real Estate Development",
        "Sharia-Compliant",
        "Semiconductors / Hardware",
        "Energy Storage / Services",
        "Shipping / Maritime",
        "Insurance / Insurtech",
        "Pet Care",
        "Consumer & Lifestyle Services",
        "Sovereign Wealth Fund",
        "Investment Banking / M&A Advisory",
        "Transportation",
        "Mobility",
        "Water / Waste Management",
        "Automotive",
        "Hospitality / Hotels / Tourism",
        "Food & Beverage / QSR",
        "Robotics / Automation",
        "Security Services",
        "Financial Services",
        "Aquaculture / Forestry",
        "Aerospace & Defense",
        "Nursery",
    }
)
